<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
   "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<title>Zend Framework Tutorial Series</title>
	<meta name="generator" content="TextMate http://macromates.com/">
	<meta name="author" content="Adler  Medrado">
	<!-- Date: 2010-02-15 -->
</head>
<body>
	<div id="header">
		<h1>Zend Framework Tutorial Series</h1>
	</div>
	<div id="content">
		<p>Este é o layout do nosso sistema. Em breve nós iremos modifica-lo.</p>
		<?php echo $this->layout()->content; ?>
	</div>
	<div id="footer">
		<p>&copy; 2010 - Adler Medrado - http://adlermedrado.com.br</p>
	</div>
</body>
</html>